import "./Testimonials.css";
import { motion } from "framer-motion";
import { Star } from "lucide-react";

const reviews = [
  {
    name: "Rahul Sharma",
    role: "Software Engineer",
    review:
      "The AI Resume Analyzer helped me optimize my resume and increase my ATS score. I got shortlisted for multiple interviews."
  },
  {
    name: "Priya Verma",
    role: "Data Analyst",
    review:
      "The job matching feature clearly showed the skills I was missing and gave me a roadmap to improve."
  },
  {
    name: "Aman Gupta",
    role: "Cybersecurity Student",
    review:
      "The interview questions generated by the AI were very close to what I faced in actual interviews."
  }
];

function Testimonials() {
  return (
    <section className="testimonials-section">

      <motion.h2
        initial={{ opacity: 0, y: 30 }}
        whileInView={{ opacity: 1, y: 0 }}
      >
        What Our Users Say
      </motion.h2>

      <p className="testimonial-subtitle">
        Thousands of students and professionals trust our AI-powered platform.
      </p>

      <div className="testimonial-grid">

        {reviews.map((review, index) => (
          <motion.div
            className="testimonial-card"
            key={index}
            whileHover={{ y: -10, scale: 1.03 }}
          >
            <div className="stars">
              {[...Array(5)].map((_, i) => (
                <Star key={i} size={18} fill="#ff8c00" color="#ff8c00" />
              ))}
            </div>

            <p>"{review.review}"</p>

            <h3>{review.name}</h3>

            <span>{review.role}</span>
          </motion.div>
        ))}

      </div>
    </section>
  );
}

export default Testimonials;